version: "3.6"

services:
  web:
    build: .
    depends_on:
      - elastic
    ports:
      - "8080:8080"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - "9200:9200"