version: "3.6"

services:
  web:
    build: .
    volumes:
      - assets:/assets
      - templates:/templates
    depends_on:
      - elastic
    ports:
      - "8080:8080"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports:
      - "9200:9200"